- name: Deploy Zergpool unit
  template:
    owner: root
    group: root
    mode: 0644
    src: galaxy-zergpool.service.j2
    dest: /etc/systemd/system/{{ galaxy_systemd_unit_name }}-zergpool.service
  when: galaxy_zergpool
  notify: daemon reload

- name: Deploy Zergling units
  template:
    owner: root
    group: root
    mode: 0644
    src: galaxy-zergling@.service.j2
    dest: /etc/systemd/system/{{ galaxy_systemd_unit_name }}-zergling@.service
  notify: daemon reload

- name: Deploy handler units
  template:
    owner: root
    group: root
    mode: 0644
    src: galaxy-handler@.service.j2
    dest: /etc/systemd/system/{{ galaxy_systemd_unit_name }}-handler@.service
  notify: daemon reload

- name: Deploy workflow units
  template:
    owner: root
    group: root
    mode: 0644
    src: galaxy-workflow-scheduler@.service.j2
    dest: /etc/systemd/system/{{ galaxy_systemd_unit_name }}-workflow-scheduler@.service
  notify: daemon reload

# TODO: In case of changes? Not sure this is necessary.
#- name: just force systemd to reread configs (2.4 and above)
  #systemd:
    #daemon_reload: yes

- name: Enable zergpool and ensure it is running
  systemd:
    name: {{ galaxy_systemd_unit_name }}-zergpool.service
    enabled: yes
    state: started
  when: galaxy_zergpool

- name: Enable relevant zerglings
  systemd:
    name: "{{ galaxy_systemd_unit_name }}-zergling@{{ item }}.service"
    enabled: yes
    state: started
  loop: "{{ range(0, galaxy_systemd_zerglings) | list }}"

- name: Enable relevant handlers
  systemd:
    name: "{{ galaxy_systemd_unit_name }}-handler@{{ item }}.service"
    enabled: yes
    state: started
  loop: "{{ range(0, galaxy_systemd_handlers) | list }}"

- name: Enable relevant workflows
  systemd:
    name: "{{ galaxy_systemd_unit_name }}-workflow-scheduler@{{ item }}.service"
    enabled: yes
    state: started
  loop: "{{ range(0, galaxy_systemd_workflow_schedulers) | list }}"
  when: galaxy_systemd_workflow_schedulers > 0
